### ISSUE TITLE
When will you release the searching code?

### ISSUE THREAD

**Issue by haowang1992** [PeterouZh/NAS_cGAN#1]
Thanks for your excellent work! I am very interested on it.

When will you release the searching code? Thanks a lot!

**Comment by PeterouZh** [comment]
Sorry for the late reply. I am refactoring the code to make it support DDP. I will release it once the refactoring is completed.

**Comment by ghost** [comment]
Same question, when will you release the searching code? 
I'm sure your work will inspire more researchers if the code is released. Thanks!

**Comment by PeterouZh** [comment]
Thanks for your attention. I decide to refactor the code from now on and strive to release it as soon as possible.
